// nextjs-demo/components/RevenueChart.tsx
"use client";

import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  Filler,
} from "chart.js";
import { Line } from "react-chartjs-2";
import { useMemo } from "react";
import { Order } from "@/types";

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  Filler
);

interface RevenueChartProps {
  orders: Order[];
  year?: number;
}

export default function RevenueChart({
  orders,
  year = new Date().getFullYear(),
}: RevenueChartProps) {
  const chartData = useMemo(() => {
    const monthlyRevenue = new Array(12).fill(0);

    orders.forEach((order) => {
      const orderDate = new Date(order.date);

      if (orderDate.getFullYear() === year && order.status === "Pagato") {
        monthlyRevenue[orderDate.getMonth()] += order.total;
      }
    });

    return {
      labels: [
        "Gen",
        "Feb",
        "Mar",
        "Apr",
        "Mag",
        "Giu",
        "Lug",
        "Ago",
        "Set",
        "Ott",
        "Nov",
        "Dic",
      ],
      datasets: [
        {
          label: `Fatturato ${year}`,
          data: monthlyRevenue,
          fill: true,
          borderColor: "#3b82f6",
          backgroundColor: "rgba(59, 130, 246, 0.2)",
          tension: 0.4,
        },
      ],
    };
  }, [orders, year]);

  const options = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        labels: {
          color: "#4b5563",
        },
      },
    },
    scales: {
      x: {
        ticks: { color: "#9ca3af" },
        grid: { color: "#e5e7eb", drawBorder: false },
      },
      y: {
        ticks: { color: "#9ca3af" },
        grid: { color: "#e5e7eb", drawBorder: false },
      },
    },
  };

  return (
    <div className="w-full h-[400px]">
      <Line options={options} data={chartData} />
    </div>
  );
}

// src/app/shared/components/revenue-chart/revenue-chart.component.ts
import { Component, input, effect } from '@angular/core';
import { Order, OrderStatus } from '../../../core/models/order.model';

@Component({
  selector: 'app-revenue-chart',
  templateUrl: './revenue-chart.component.html',
  styleUrls: ['./revenue-chart.component.scss'],
  standalone: false,
})
export class RevenueChartComponent {
  orders = input<Order[]>([]);
  year = input<number>(new Date().getFullYear());

  data: any;
  options: any;

  constructor() {
    effect(() => {
      this.updateChart(this.orders(), this.year());
    });
  }

  private updateChart(orders: Order[], year: number) {
    const monthlyRevenue = new Array(12).fill(0);

    orders.forEach((order) => {
      const orderDate = new Date(order.date);
      if (
        orderDate.getFullYear() === year &&
        order.status === OrderStatus.Paid
      ) {
        monthlyRevenue[orderDate.getMonth()] += order.total;
      }
    });

    const documentStyle = getComputedStyle(document.documentElement);
    const textColor = documentStyle.getPropertyValue('--text-color');
    const textColorSecondary = documentStyle.getPropertyValue(
      '--text-color-secondary'
    );
    const surfaceBorder = documentStyle.getPropertyValue('--surface-border');

    this.data = {
      labels: [
        'Gen',
        'Feb',
        'Mar',
        'Apr',
        'Mag',
        'Giu',
        'Lug',
        'Ago',
        'Set',
        'Ott',
        'Nov',
        'Dic',
      ],
      datasets: [
        {
          label: `Fatturato ${year}`,
          data: monthlyRevenue,
          fill: true,
          borderColor: documentStyle.getPropertyValue('--blue-500'),
          backgroundColor: 'rgba(63, 81, 181, 0.2)',
          tension: 0.4,
        },
      ],
    };

    this.options = {
      maintainAspectRatio: false,
      aspectRatio: 0.6,
      plugins: {
        legend: {
          labels: {
            color: textColor,
          },
        },
      },
      scales: {
        x: {
          ticks: {
            color: textColorSecondary,
          },
          grid: {
            color: surfaceBorder,
            drawBorder: false,
          },
        },
        y: {
          ticks: {
            color: textColorSecondary,
          },
          grid: {
            color: surfaceBorder,
            drawBorder: false,
          },
        },
      },
    };
  }
}

<div class="chart-wrapper">
  <canvas
    baseChart
    [data]="lineChartData"
    [options]="lineChartOptions"
    [type]="'line'"
    [legend]="lineChartLegend"
  >
  </canvas>
</div>
