// src/app/core/layout/components/sidebar/sidebar.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.scss'],
  standalone: false,
})
export class SidebarComponent {}

<aside
  class="bg-white border-t md:border-t-0 md:border-r border-gray-200 z-50 fixed bottom-0 w-full h-16 md:relative md:h-full md:w-[260px] md:flex md:flex-col md:shrink-0"
>
  <div
    class="hidden md:flex h-16 items-center justify-center border-b border-gray-100 cursor-pointer"
    routerLink="/dashboard"
  >
    <img
      src="images/logo-transparent-bg.png"
      alt="ApexFlow Logo"
      class="max-h-[48px] max-w-[90%] object-contain"
    />
  </div>

  <nav
    class="flex flex-row items-center justify-around h-full gap-2 px-6 md:flex-col md:items-stretch md:justify-start md:h-auto md:flex-1 md:overflow-y-auto md:p-4"
  >
    <div
      class="hidden md:block px-2 pt-4 pb-2 text-xs font-bold text-gray-400 uppercase tracking-wider"
    >
      Menu Principale
    </div>

    <a
      routerLink="/dashboard"
      routerLinkActive="bg-indigo-50 text-indigo-700 font-semibold"
      class="flex-1 md:flex-none flex flex-col md:flex-row items-center justify-center md:justify-start p-2 md:px-4 md:py-3 rounded-lg text-gray-600 hover:bg-indigo-50 hover:text-indigo-600 transition-all gap-1 md:gap-3"
    >
      <i class="pi pi-th-large text-xl md:text-lg"></i>
      <span class="text-[10px] md:text-base">Dashboard</span>
    </a>

    <div
      class="hidden md:block px-2 pt-4 pb-2 text-xs font-bold text-gray-400 uppercase tracking-wider"
    >
      Gestione
    </div>

    <a
      routerLink="/customers"
      routerLinkActive="bg-indigo-50 text-indigo-700 font-semibold"
      class="flex-1 md:flex-none flex flex-col md:flex-row items-center justify-center md:justify-start p-2 md:px-4 md:py-3 rounded-lg text-gray-600 hover:bg-indigo-50 hover:text-indigo-600 transition-all gap-1 md:gap-3"
    >
      <i class="pi pi-users text-xl md:text-lg"></i>
      <span class="text-[10px] md:text-base">Clienti</span>
    </a>

    <a
      routerLink="/orders"
      routerLinkActive="bg-indigo-50 text-indigo-700 font-semibold"
      class="flex-1 md:flex-none flex flex-col md:flex-row items-center justify-center md:justify-start p-2 md:px-4 md:py-3 rounded-lg text-gray-600 hover:bg-indigo-50 hover:text-indigo-600 transition-all gap-1 md:gap-3"
    >
      <i class="pi pi-box text-xl md:text-lg"></i>
      <span class="text-[10px] md:text-base">Ordini</span>
    </a>

    <!-- Spacer for Desktop to push bottom items -->
    <div class="hidden md:block md:mt-auto"></div>

    <a
      routerLink="/settings"
      routerLinkActive="bg-indigo-50 text-indigo-700 font-semibold"
      class="flex-1 md:flex-none flex flex-col md:flex-row items-center justify-center md:justify-start p-2 md:px-4 md:py-3 rounded-lg text-gray-600 hover:bg-indigo-50 hover:text-indigo-600 transition-all gap-1 md:gap-3"
    >
      <i class="pi pi-cog text-xl md:text-lg"></i>
      <span class="text-[10px] md:text-base">Settings</span>
    </a>

    <a
      href="https://github.com/xdelmo/dashboard-tesi"
      target="_blank"
      class="hidden md:flex items-center px-4 py-3 text-gray-500 hover:text-gray-800 rounded-lg hover:bg-gray-100 transition-colors gap-3"
    >
      <img src="/images/github-mark.png" class="h-4" />
      <span>Repository GitHub</span>
    </a>
  </nav>
</aside>

// nextjs-demo/components/Sidebar.tsx
"use client";

import Link from "next/link";
import Image from "next/image";
import { usePathname } from "next/navigation";

const navItems = [
  { name: "Dashboard", href: "/", icon: "pi pi-th-large" },
  { name: "Clienti", href: "/customers", icon: "pi pi-users" },
  { name: "Ordini", href: "/orders", icon: "pi pi-shopping-cart" },
  { name: "Prodotti", href: "/products", icon: "pi pi-tags" },
];

export default function Sidebar() {
  const pathname = usePathname();

  return (
    <div className="flex flex-col h-full bg-white border-r border-gray-200">
      <div className="h-20 flex items-center justify-center border-b border-gray-100">
        <Link
          href="/"
          className="flex items-center justify-center relative w-full h-full px-6"
        >
          <Image
            src="/images/logo-transparent-bg.png"
            alt="ApexFlow Logo"
            width={150}
            height={48}
            className="object-contain w-auto h-12"
            priority
          />
        </Link>
      </div>

      <nav className="flex-1 px-4 py-6 space-y-2 overflow-y-auto">
        <div className="px-2 pb-2 text-xs font-bold text-gray-400 uppercase tracking-wider">
          Menu Principale
        </div>

        {navItems.slice(0, 1).map((item) => {
          const isActive = pathname === item.href;
          return (
            <Link
              key={item.href}
              href={item.href}
              className={`flex items-center gap-3 px-4 py-3 rounded-lg transition-all ${
                isActive
                  ? "bg-indigo-50 text-indigo-700 font-semibold"
                  : "text-gray-600 hover:bg-indigo-50 hover:text-indigo-600"
              }`}
            >
              <i className={`${item.icon} text-lg`}></i>
              <span className="text-base">{item.name}</span>
            </Link>
          );
        })}

        <div className="px-2 pt-4 pb-2 text-xs font-bold text-gray-400 uppercase tracking-wider">
          Gestione
        </div>

        {navItems.slice(1).map((item) => {
          const isActive = pathname.startsWith(item.href) && item.href !== "/";
          return (
            <Link
              key={item.href}
              href={item.href}
              className={`flex items-center gap-3 px-4 py-3 rounded-lg transition-all ${
                isActive
                  ? "bg-indigo-50 text-indigo-700 font-semibold"
                  : "text-gray-600 hover:bg-indigo-50 hover:text-indigo-600"
              }`}
            >
              <i className={`${item.icon} text-lg`}></i>
              <span className="text-base">{item.name}</span>
            </Link>
          );
        })}
        <div className="my-4 border-t border-gray-100" />

        <a
          href="https://github.com/xdelmo/dashboard-tesi/tree/feature/nextjs-demo/nextjs-demo"
          target="_blank"
          className="hidden md:flex items-center px-4 py-3 text-gray-500 hover:text-gray-800 rounded-lg hover:bg-gray-100 transition-colors gap-3"
        >
          <img src="/images/github-mark.png" className="h-4" />
          <span>Branch GitHub</span>
        </a>
      </nav>
    </div>
  );
}
